name: on-push
on:
  push:
    branches: [main]
jobs:
  vocal:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Checkout
        uses: actions/checkout@v3

      - name: Lint
        run: cargo clippy

      - name: Test
        run: cargo test

      - name: Build Release
        run: cargo build --release
